@startuml

!theme materia-outline

skinparam ArrowColor #9803fc
skinparam BackgroundColor #FFFFFF
skinparam ObjectBorderColor #9803fc
skinparam ObjectFontColor #9803fc

object Player
object Inventory
object Item
object Section
object Enemy
object Game
object Map

Player "1" *-- "1" Inventory: Has
Inventory "1" *-- "*" Item: Has
Player "1" --> "*" Enemy: Fights
Player "1" --> "1" Game: Plays
Player "1" --* "*" Section: Is in
Enemy "1" *-- "1" Section: Is in
Item "*" --* "1" Section: Is in
Player "1" *-- "*" Item: Uses
Game "1" *-- "1" Map: Has
Map "1" *-- "1..*" Section : Has
@enduml