@startuml
!theme materia-outline

skinparam ArrowColor #9803fc
skinparam BackgroundColor #FFFFFF
skinparam ArrowColor #9803fc
skinparam ActorBorderColor #9803fc
skinparam ActorFontColor #9803fc
skinparam ActorBackgroundColor #9803fc
skinparam ParticipantFontColor #9803fc
skinparam ParticipantBorderColor #9803fc
skinparam ParticipantBackgroundColor #FFFFFF
skinparam {
 SequenceGroupBorderColor #9803fc
}

actor Player
participant Game
participant StorageService

loop while !Game.EXIT
  alt command=newGame
    Player -> Game: newGame(playerName)
    Game -> StorageService: Requests a new game for the player.
    StorageService -> Game: Game object.
    Game -> Game: Populates game object.
  else command=loadGame
    Player -> Game: loadGame(gameId)
    Game -> StorageService: Game object request.
    StorageService -> Game: Game object.
    Game -> Game: Populates game object.
  else command=listGames
    Player -> Game: listGames
    Game -> StorageService: Game list request.
    StorageService -> Game: List of games.
    Game -> Player: Shows the list of games.
  else command=deleteGame
    Player -> Game: deleteGame
    Game -> StorageService: Delete game object request.
  end

  loop while !Player.hasWon and !Player.hasDied)
    Player -> Game: Player enters a command.
    Game -> Game: Command parse and validation.

    alt command=save
      Game -> StorageService: Request to save current game object
    else else
      Game -> Game: Game state update.
    end

    Game -> Player: Command output may be:\n1) Input request for the user\n2) Command result
    opt The command requested a new input
      Player -> Game: Input specific data
      Game -> Player: Output specific data
    end
  end
end

@enduml