@startuml
!theme materia-outline

skinparam ArrowColor #9803fc
skinparam BackgroundColor #FFFFFF
skinparam ArrowColor #9803fc
skinparam ActorBorderColor #9803fc
skinparam ActorFontColor #9803fc
skinparam ActorBackgroundColor #9803fc
skinparam ParticipantFontColor #9803fc
skinparam ParticipantBorderColor #9803fc
skinparam ParticipantBackgroundColor #FFFFFF
skinparam {
 SequenceGroupBorderColor #9803fc
}


participant CmdFight
participant CmdRun
participant "I/O Stream"
participant ApplicationContext
participant Game
participant Player

CmdFight++
CmdFight -> CmdRun++: run

CmdRun -> ApplicationContext++: getGame()
ApplicationContext --> CmdRun
ApplicationContext--

CmdRun -> Game++: getPlayer()
Game --> CmdRun
Game--

CmdRun -> Player: setFightingStatus()

CmdRun -> "I/O Stream": Notify that the player ran away from the fight.


@enduml